# Generated by Django 5.0 on 2025-05-12 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DevelopmentProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("location", models.CharField(max_length=200)),
                ("developer", models.CharField(max_length=120)),
                ("general_contractor", models.CharField(max_length=120)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("townhouse", "Townhouse"),
                            ("villa", "Villa"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("delivery_time", models.DateField()),
                ("completion_standard", models.CharField(max_length=100)),
                ("management_unit", models.CharField(max_length=120)),
                ("distributor", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="RealEstateProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("area", models.DecimalField(decimal_places=2, max_digits=8)),
                ("location", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "for_sale",
                    models.BooleanField(help_text="True = sale, False = rent"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("land", "Land"),
                            ("townhouse", "Townhouse"),
                            ("villa", "Villa"),
                            ("apartment", "Apartment"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="listings.developmentproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandLotDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("road_frontage", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_details",
                        to="listings.realestateproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApartmentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor_number", models.PositiveSmallIntegerField()),
                ("bedrooms", models.PositiveSmallIntegerField()),
                ("bathrooms", models.PositiveSmallIntegerField()),
                ("balcony", models.BooleanField()),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartment_details",
                        to="listings.realestateproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TownhouseDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floors", models.PositiveSmallIntegerField()),
                ("bedrooms", models.PositiveSmallIntegerField()),
                ("bathrooms", models.PositiveSmallIntegerField()),
                ("living_room", models.BooleanField()),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="townhouse_details",
                        to="listings.realestateproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VillaDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floors", models.PositiveSmallIntegerField()),
                ("bedrooms", models.PositiveSmallIntegerField()),
                ("bathrooms", models.PositiveSmallIntegerField()),
                ("living_room", models.BooleanField()),
                ("garden", models.BooleanField()),
                ("swimming_pool", models.BooleanField()),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villa_details",
                        to="listings.realestateproduct",
                    ),
                ),
            ],
        ),
    ]
