# Generated by Django 5.0 on 2025-05-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_productmedia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmedia",
            options={"ordering": ["order", "uploaded_at"]},
        ),
        migrations.AddField(
            model_name="productmedia",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
