# Generated by Django 5.0 on 2025-05-14 02:41

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_productmedia_options_productmedia_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmedia",
            name="file",
            field=models.FileField(upload_to=listings.models.product_media_path),
        ),
        migrations.AlterField(
            model_name="realestateproduct",
            name="id",
            field=models.CharField(
                editable=False, max_length=10, primary_key=True, serialize=False
            ),
        ),
    ]
