# Generated by Django 5.0 on 2025-07-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_alter_productmedia_file_alter_realestateproduct_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="townhousedetails",
            name="garage",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
