# Generated by Django 5.0 on 2025-07-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_townhousedetails_garage"),
    ]

    operations = [
        migrations.AddField(
            model_name="townhousedetails",
            name="interior",
            field=models.TextField(default="Đang cập nhật"),
        ),
        migrations.AddField(
            model_name="townhousedetails",
            name="policy",
            field=models.TextField(default="Đang cập nhật"),
        ),
        migrations.AddField(
            model_name="townhousedetails",
            name="structure",
            field=models.TextField(default="Đang cập nhật"),
        ),
    ]
