# Generated by Django 5.0 on 2025-07-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_townhousedetails_interior_townhousedetails_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="villadetails",
            name="garage",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
