# Generated by Django 5.0 on 2025-07-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_villadetails_garage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developmentproject",
            name="id",
            field=models.CharField(
                editable=False, max_length=10, primary_key=True, serialize=False
            ),
        ),
    ]
