# Generated by Django 5.0 on 2025-07-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_alter_developmentproject_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="developmentproject",
            name="area_size",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Area in hectares (Ha)",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="developmentproject",
            name="policy",
            field=models.TextField(
                default="Đang cập nhật", help_text="Policy information (e.g., Sổ hồng)"
            ),
        ),
        migrations.AddField(
            model_name="developmentproject",
            name="quantity",
            field=models.CharField(
                default="Đang cập nhật",
                help_text="Number of units (e.g., 231 căn)",
                max_length=50,
            ),
        ),
    ]
