# Generated by Django 5.0 on 2025-07-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_developmentproject_area_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developmentproject",
            name="completion_standard",
            field=models.CharField(default="Đang cập nhật", max_length=100),
        ),
    ]
