# Generated by Django 5.0 on 2025-09-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0010_alter_developmentproject_completion_standard"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestateproduct",
            name="tiktok_url",
            field=models.URLField(
                blank=True,
                help_text="TikTok video URL for this product",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="realestateproduct",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube video URL for this product",
                max_length=500,
                null=True,
            ),
        ),
    ]
