# Generated by Django 5.0 on 2025-09-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0011_realestateproduct_tiktok_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestateproduct",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Latitude coordinate (e.g., 10.7756590)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="realestateproduct",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Longitude coordinate (e.g., 106.7019090)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
