# Generated by Django 5.0 on 2025-09-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0012_realestateproduct_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestateproduct",
            name="mini_description",
            field=models.CharField(
                blank=True,
                help_text="Short description for list views. If empty, will use truncated description.",
                max_length=200,
                null=True,
            ),
        ),
    ]
